### ISSUE TITLE
Can't Connect to the ARRIS TG862A Advanced Section

### ISSUE THREAD

**Issue by vs0uz4** [borfast/arrispwgen-cli#2]
Hi!

Could you tell me why I can't connect to the ARRIS TG862A modem?

I performed the installation of the "npm" package according to the documentation specifications, but as you can see in the images, it always gives the error "INVALID PASSWORD"

![Captura de tela de 2020-10-04 22-16-19](https://user-images.githubusercontent.com/2080547/95032588-86693b00-0691-11eb-8459-bfcb4c07cf11.png)

![Captura de tela de 2020-10-04 22-16-09](https://user-images.githubusercontent.com/2080547/95032598-92ed9380-0691-11eb-94af-a8790e3dd6d4.png)

**Comment by SnailShea** [comment]
I'm a bit late to this issue but the problem is probably that your ISP is using a custom seed. If you don't know the seed, you can't generate the appropriate password. I doubt this is an issue with the arrispwgen software itself.

**Comment by borfast** [comment]
Sorry @vs0uz4, somehow I missed your comment and never saw it all this time :raised_eyebrow: 

But it's pretty much as @MxLinux said and I'm afraid there's not much to be done.

@MxLinux, thanks for jumping in, by the way. :+1:
